### PR TITLE
Step-by-step guide with examples for The Things Network

### PR DESCRIPTION
**Pull request by janakj**
This is a step-by-step guide with examples that describes how to connect a Hardwario LoRa device to The Things Network. I originally wrote the guide for my students working on hands-on IoT projects, but perhaps it could be of interest to the wider Hardwario developer community.

Please feel free to include the guide in your documentation if you like. It is in the public domain.

### CODE REVIEW

**Comment by hubmartin** [comment]
@janakj Thanks a lot! This is great improvement and mainly it is up-to-date.
I'll will focus more on TOWER for some time again, so I'll improve docs. And creating TTN OTAA tutorial was my first goal. So I'll merge it for now and then edit and update other parts of LoRa docs later. 
Thanks

**Comment by janakj** [comment]
Thanks a weekend merge.

One particular detail that could use your review are the LoRaWAN (MAC) and PHY version settings. I was not really sure what is supported by the Murata firmware. I picked somewhat conservative settings that work with my modules, but maybe those are not the most efficient or the most recent.

**Comment by hubpav** [comment]
@janakj Murata vendor firmware supports LoRaWAN specification v1.0.2 rev. B. Thanks.

**Comment by janakj** [comment]
@hubmartin Thanks! I will be joining another device to TTN this coming week, so I'll test it out and if it works, update the guide.

I think I tried 1.0.2 rev. B before and it did not work for me, but I had older firmware in the Core module then which did not provide AT$FRESET. That AT command is a life saver, by the way.

**Comment by hubpav** [comment]
@janakj This is the statement from the vendor changelog for firmware version 1.1.06:

`LoRaWAN Specification 1.0.2 and LoRaWAN Regional Parameters Specification v1.0.2rB.`

**Pull request merged**
